[package]
name = "term_office"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.8"
mairs = "0.1.6"
pdf = "0.9.0"
serde-xml-rs = "0.6.0"
